# Generated by Django 3.2.3 on 2021-06-21 11:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/static/default.png', upload_to=accounts.models.create_path),
        ),
    ]
