# Generated by Django 3.2.3 on 2021-06-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20210622_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='name',
            field=models.CharField(default='untitledFolder', max_length=200),
        ),
    ]
